#! /usr/bin/python3

TOP_LEVEL_ENTITY = "TOP"
CHIP_SELECT="Stratix V GX"
#CHIP_SELECT="MAX V CPLD"
def print_pcml1p4(name, location):
  print(f"set_location_assignment PIN_{location} -to {name}")
  print(f"set_instance_assignment -name IO_STANDARD \"1.4-V PCML\" -to {name}")
def print_sstl1p5(name, location):
  print(f"set_location_assignment PIN_{location} -to {name}")
  print(f"set_instance_assignment -name IO_STANDARD \"SSTL-15 CLASS I\" -to {name}")
def print_diff1p5(name, location):
  print(f"set_location_assignment PIN_{location} -to {name}")
  print(f"set_instance_assignment -name IO_STANDARD \"DIFFERENTIAL 1.5-V SSTL CLASS I\" -to {name}")
def print_1p8(name, location):
  print(f"set_location_assignment PIN_{location} -to {name}")
  print(f"set_instance_assignment -name IO_STANDARD \"1.8 V\" -to {name}")
def print_cmos2p5(name, location):
  print(f"set_location_assignment PIN_{location} -to {name}")
  print(f"set_instance_assignment -name IO_STANDARD \"2.5 V CMOS\" -to {name}")
def print_2p5(name, location):
  print(f"set_location_assignment PIN_{location} -to {name}")
  print(f"set_instance_assignment -name IO_STANDARD \"2.5 V\" -to {name}")
def print_diff2p5(name, location):
  print(f"set_location_assignment PIN_{location} -to {name}")
  print(f"set_instance_assignment -name IO_STANDARD \"DIFFERENTIAL 2.5-V SSTL CLASS II\" -to {name}")
def print_3p3(name, location):
  print(f"set_location_assignment PIN_{location} -to {name}")
  print(f"set_instance_assignment -name IO_STANDARD \"3.3 V\" -to {name}")
def print_lvttl3p3(name, location):
  print(f"set_location_assignment PIN_{location} -to {name}")
  print(f"set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to {name}")
def print_lvds(name, location):
  print(f"set_location_assignment PIN_{location} -to {name}")
  print(f"set_instance_assignment -name IO_STANDARD \"LVDS\" -to {name}")

def print_device():
  print(f"#============================================================")
  print(f"# Device")
  print(f"#============================================================")
  if CHIP_SELECT == "Stratix V GX":
    print(f"set_global_assignment -name FAMILY \"Stratix V\"")
    print(f"set_global_assignment -name DEVICE 5SGXEA7K2F40C")
    print(f"set_global_assignment -name TOP_LEVEL_ENTITY {TOP_LEVEL_ENTITY}")
    print(f"set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files")
    print(f"set_global_assignment -name EDA_SIMULATION_TOOL \"ModelSim-Altera (VHDL)\"")
print_device()

def print_clock():
  print(f"#============================================================")
  print(f"# CLOCK")
  print(f"#============================================================")
  if CHIP_SELECT == "Stratix V GX":
    print_1p8 ("CLKIN_50"     , "AN6")
    print_lvds("REFCLK1_QL0_P", "AD33")
    print_lvds("REFCLK1_QL0_N", "AD34")
    print_lvds("CLKINBOT_P0"  , "AH22")
    print_lvds("CLKINBOT_N0"  , "AJ22")
    print_lvds("CLKINTOP_P0"  , "J23")
    print_lvds("CLKINTOP_N0"  , "J24")
    print_lvds("REFCLK4_QR2_P", "V6")
    print_lvds("REFCLK4_QR2_N", "V5")
    print_lvds("CLK_125_P"    , "AV29")
    print_lvds("CLK_125_N"    , "AW29")
print_clock()

def print_reset():
  print(f"#============================================================")
  print(f"# RESET")
  print(f"#============================================================")
  if CHIP_SELECT == "Stratix V GX":
    print_2p5("CPU_RESETn", "AM34")
print_reset()

def print_flash():
  print(f"#============================================================")
  print(f"# FLASH MEMORY")
  print(f"#============================================================")
  if CHIP_SELECT == "Stratix V GX":
    print_1p8("FLASH_ADVn"      , "AP7")
    print_1p8("FLASH_CEn[0]"    , "AV14")
    print_1p8("FLASH_CEn[1]"    , "AW13")
    print_1p8("FLASH_CLK"       , "AM8")
    print_1p8("FLASH_OEn"       , "AJ7")
    print_1p8("FLASH_RDYBSYN[0]", "AL6")
    print_1p8("FLASH_RDYBSYN[1]", "AN7")
    print_1p8("FLASH_RESETn"    , "AJ6")
    print_1p8("FLASH_WEn"       , "AN8")
print_flash()

def print_push_button():
  print(f"#============================================================")
  print(f"# PUSH BUTTON")
  print(f"#============================================================")  
  if CHIP_SELECT == "Stratix V GX":
    print_2p5("USER_PB[0]", "A7")
    print_2p5("USER_PB[1]", "B7")
    print_2p5("USER_PB[2]", "C7")
print_push_button()

def print_dipsw():
  print(f"#============================================================")
  print(f"# DIPSW")
  print(f"#============================================================")
  if CHIP_SELECT == "Stratix V GX":
    dipsw_pins = ["E7", "H7", "J7", "K7", "M6", "N6", "P7", "N7"]
    for a in range(len(dipsw_pins)):
      print_2p5(f"USER_DIPSW[{a}]", dipsw_pins[a])
print_dipsw()

def print_led():
  print(f"#============================================================")
  print(f"# LED")
  print(f"#============================================================")
  if CHIP_SELECT == "Stratix V GX":
    ledr_pins = ["AH28", "AG30", "AL7", "AR24", "AM7", "AW7", "AL23", "AV7"]
    ledg_pins = ["J11", "U10", "U9", "AU24", "AF28", "AE29", "AR7", "AV10"]
    print_2p5(f"USER_LED_R[0]", ledr_pins[0])
    print_2p5(f"USER_LED_R[1]", ledr_pins[1])
    print_1p8(f"USER_LED_R[2]", ledr_pins[2])
    print_1p8(f"USER_LED_R[3]", ledr_pins[3])
    print_1p8(f"USER_LED_R[4]", ledr_pins[4])
    print_1p8(f"USER_LED_R[5]", ledr_pins[5])
    print_1p8(f"USER_LED_R[6]", ledr_pins[6])
    print_1p8(f"USER_LED_R[7]", ledr_pins[7])
    print_2p5(f"USER_LED_G[0]", ledg_pins[0])
    print_2p5(f"USER_LED_G[1]", ledg_pins[1])
    print_2p5(f"USER_LED_G[2]", ledg_pins[2])
    print_1p8(f"USER_LED_G[3]", ledg_pins[3])
    print_2p5(f"USER_LED_G[4]", ledg_pins[4])
    print_2p5(f"USER_LED_G[5]", ledg_pins[5])
    print_1p8(f"USER_LED_G[6]", ledg_pins[6])
    print_2p5(f"USER_LED_G[7]", ledg_pins[7])
print_led()

def print_lcd():
  print(f"#============================================================")
  print(f"# LCD")
  print(f"#============================================================")
  if CHIP_SELECT == "Stratix V GX":
    print_2p5("LCD_D_Cn"    , "AH10")
    print_2p5("LCD_WEn"     , "AW10")
    print_2p5("LCD_CSn"     , "AU9")
    lcd_data_pins = ["AP10", "AN10", "AM10", "AL10", "AP9", "AN9", "AT9", "AR9"]
    for a in range(len(lcd_data_pins)):
      print_2p5(f"LCD_DATA[{a}]" , lcd_data_pins[a])
print_lcd()

def print_hsmc():
  print(f"#============================================================")
  print(f"# HSMC")
  print(f"#============================================================")
  if CHIP_SELECT == "Stratix V GX":
    hsmc_a_pins = ["AG28", "AT8" , "G6"  , "AR8" , "G7"  , "AJ10", "AH9" , "G8"  , "AG9" , "G9"  ,
                   "AV2" , "AV1" , "AP2" , "AP1" , "AM2" , "AM1" , "AK2" , "AK1" , "AH2" , "AH1" ,
                   "AF2" , "AF1" , "AD2" , "AD1" , "AB2" , "AB1" , "AU4" , "AU3" , "AN4" , "AN3" ,
                   "AL4" , "AL3" , "AJ4" , "AJ3" , "AG4" , "AG3" , "AE4" , "AE3" , "AC4" , "AC3" , 
                   "AA4" , "AA3" , "AJ29", "AK29", "AR28", "AP28", "AW8" , "AM29", "AL29", "AW11",
                   "AU12", "AR12", "AK12", "AJ12", "AG10", "AE12", "AG10", "R9"  , "L9"  , "L8"  ,
                   "G11" , "F9"  , "E8"  , "E11" , "C9"  , "A10" , "AV11", "AT12", "AR11", "AL12",
                   "AH12", "AF10", "AD12", "AB10", "T9"  , "M9"  , "M8"  , "H11" , "G10" , "F8"  ,
                   "F11" , "C8"  , "B10" , "AU11", "AN11", "AL11", "AF11", "AE11", "AE9" , "AC9" ,
                   "AC12", "P8"  , "N10" , "N9"  , "J9"  , "H10" , "D9"  , "C10" , "A11" , "B8"  ,
                   "AT11", "AM11", "AK11", "AG12", "AE10", "AD9" , "AB9" , "AB12", "R8"  , "P10" ,
                   "N8"  , "K9"  , "J10" , "E9"  , "D10" , "B11" , "A8"]
    for a in range(len(hsmc_a_pins)):
      print_2p5(f"HSMA[{a}]", hsmc_a_pins[a])
    print_2p5("HSMA_CLK_IN[0]"   , hsmc_a_pins[0])
    print_2p5("HSMA_GPIO[1]"     , hsmc_a_pins[0])
    print_2p5("HSMA_CLK_IN_N[1]" , hsmc_a_pins[1])
    print_2p5("HSMA_CLK_IN_N[2]" , hsmc_a_pins[2])
    print_2p5("HSMA_LED_G_A[9]"  , hsmc_a_pins[2])
    print_2p5("HSMA_CLK_IN_P[1]" , hsmc_a_pins[3])
    print_2p5("HSMA_GPIO[39]"    , hsmc_a_pins[3])
    print_2p5("HSMA_CLK_IN_P[2]" , hsmc_a_pins[4])
    print_2p5("HSMA_LED_R_A[9]"  , hsmc_a_pins[4])
    print_2p5("HSMA_CLK_OUT[0]"  , hsmc_a_pins[5])
    print_2p5("HSMA_GPIO[0]"     , hsmc_a_pins[5])
    print_2p5("HSMA_CLK_OUT_N[1]", hsmc_a_pins[6])
    print_2p5("HSMA_CLK_OUT_N[2]", hsmc_a_pins[7])
    print_2p5("HSMA_LED_G_C[9]"  , hsmc_a_pins[7])
    print_2p5("HSMA_CLK_OUT_P[1]", hsmc_a_pins[8])
    print_2p5("HSMA_GPIO[38]"    , hsmc_a_pins[8])
    print_2p5("HSMA_CLK_OUT_P[2]", hsmc_a_pins[9])
    print_2p5("HSMA_LED_R_C[9]"  , hsmc_a_pins[9])
    print_2p5("HSMA_RX_P[0]"     , hsmc_a_pins[10])
    print_2p5("HSMA_RX_N[0]"     , hsmc_a_pins[11])
    print_2p5("HSMA_RX_P[1]"     , hsmc_a_pins[12])
    print_2p5("HSMA_RX_N[1]"     , hsmc_a_pins[13])
    print_2p5("HSMA_RX_P[2]"     , hsmc_a_pins[14])
    print_2p5("HSMA_RX_N[2]"     , hsmc_a_pins[15])
    print_2p5("HSMA_RX_P[3]"     , hsmc_a_pins[16])
    print_2p5("HSMA_RX_N[3]"     , hsmc_a_pins[17])
    print_2p5("HSMA_RX_P[4]"     , hsmc_a_pins[18])
    print_2p5("HSMA_RX_N[4]"     , hsmc_a_pins[19])
    print_2p5("HSMA_RX_P[5]"     , hsmc_a_pins[20])
    print_2p5("HSMA_RX_N[5]"     , hsmc_a_pins[21])
    print_2p5("HSMA_RX_P[6]"     , hsmc_a_pins[22])
    print_2p5("HSMA_RX_N[6]"     , hsmc_a_pins[23])
    print_2p5("HSMA_RX_P[7]"     , hsmc_a_pins[24])
    print_2p5("HSMA_RX_N[7]"     , hsmc_a_pins[25])
    print_2p5("HSMA_TX_P[0]"     , hsmc_a_pins[26])
    print_2p5("HSMA_TX_N[0]"     , hsmc_a_pins[27])
    print_2p5("HSMA_TX_P[1]"     , hsmc_a_pins[28])
    print_2p5("HSMA_TX_N[1]"     , hsmc_a_pins[29])
    print_2p5("HSMA_TX_P[2]"     , hsmc_a_pins[30])
    print_2p5("HSMA_TX_N[2]"     , hsmc_a_pins[31])
    print_2p5("HSMA_TX_P[3]"     , hsmc_a_pins[32])
    print_2p5("HSMA_TX_N[3]"     , hsmc_a_pins[33])
    print_2p5("HSMA_TX_P[4]"     , hsmc_a_pins[34])
    print_2p5("HSMA_TX_N[4]"     , hsmc_a_pins[35])
    print_2p5("HSMA_TX_P[5]"     , hsmc_a_pins[36])
    print_2p5("HSMA_TX_N[5]"     , hsmc_a_pins[37])
    print_2p5("HSMA_TX_P[6]"     , hsmc_a_pins[38])
    print_2p5("HSMA_TX_N[6]"     , hsmc_a_pins[39])
    print_2p5("HSMA_TX_P[7]"     , hsmc_a_pins[40])
    print_2p5("HSMA_TX_N[7]"     , hsmc_a_pins[41])
    print_2p5("HSMA_D[0]"        , hsmc_a_pins[42])
    print_2p5("HSMA_GPIO[2]"     , hsmc_a_pins[42])
    print_2p5("HSMA_D[1]"        , hsmc_a_pins[43])
    print_2p5("HSMA_GPIO[3]"     , hsmc_a_pins[43])
    print_2p5("HSMA_D[2]"        , hsmc_a_pins[44])
    print_2p5("HSMA_GPIO[4]"     , hsmc_a_pins[44])
    print_2p5("HSMA_D[3]"        , hsmc_a_pins[45])
    print_2p5("HSMA_GPIO[5]"     , hsmc_a_pins[45])
    print_2p5("HSMA_PRSNTn"      , hsmc_a_pins[46])
    print_2p5("HSMA_SCL"         , hsmc_a_pins[47])
    print_2p5("HSMA_SDA"         , hsmc_a_pins[48])
    print_2p5("HSMA_RX_D_N[0]"   , hsmc_a_pins[49])
    print_2p5("HSMA_GPIO[9]"     , hsmc_a_pins[49])
    print_2p5("HSMA_RX_D_N[1]"   , hsmc_a_pins[50])
    print_2p5("HSMA_GPIO[13]"    , hsmc_a_pins[50])
    print_2p5("HSMA_RX_D_N[2]"   , hsmc_a_pins[51])
    print_2p5("HSMA_GPIO[17]"    , hsmc_a_pins[51])
    print_2p5("HSMA_RX_D_N[3]"   , hsmc_a_pins[52])
    print_2p5("HSMA_GPIO[21]"    , hsmc_a_pins[52])
    print_2p5("HSMA_RX_D_N[4]"   , hsmc_a_pins[53])
    print_2p5("HSMA_GPIO[25]"    , hsmc_a_pins[53])
    print_2p5("HSMA_RX_D_N[5]"   , hsmc_a_pins[54])
    print_2p5("HSMA_GPIO[29]"    , hsmc_a_pins[54])
    print_2p5("HSMA_RX_D_N[6]"   , hsmc_a_pins[55])
    print_2p5("HSMA_GPIO[33]"    , hsmc_a_pins[55])
    print_2p5("HSMA_RX_D_N[7]"   , hsmc_a_pins[56])
    print_2p5("HSMA_GPIO[37]"    , hsmc_a_pins[56])
    print_2p5("HSMA_RX_D_N[8]"   , hsmc_a_pins[57])
    print_2p5("HSMA_LED_G_A[0]"  , hsmc_a_pins[57])
    print_2p5("HSMA_RX_D_N[9]"   , hsmc_a_pins[58])
    print_2p5("HSMA_LED_G_A[1]"  , hsmc_a_pins[58])
    print_2p5("HSMA_RX_D_N[10]"  , hsmc_a_pins[59])
    print_2p5("HSMA_LED_G_A[2]"  , hsmc_a_pins[59])
    print_2p5("HSMA_RX_D_N[11]"  , hsmc_a_pins[60])
    print_2p5("HSMA_LED_G_A[3]"  , hsmc_a_pins[60])
    print_2p5("HSMA_RX_D_N[12]"  , hsmc_a_pins[61])
    print_2p5("HSMA_LED_G_A[4]"  , hsmc_a_pins[61])
    print_2p5("HSMA_RX_D_N[13]"  , hsmc_a_pins[62])
    print_2p5("HSMA_LED_G_A[5]"  , hsmc_a_pins[62])
    print_2p5("HSMA_RX_D_N[14]"  , hsmc_a_pins[63])
    print_2p5("HSMA_LED_G_A[6]"  , hsmc_a_pins[63])
    print_2p5("HSMA_RX_D_N[15]"  , hsmc_a_pins[64])
    print_2p5("HSMA_LED_G_A[7]"  , hsmc_a_pins[64])
    print_2p5("HSMA_RX_D_N[16]"  , hsmc_a_pins[65])
    print_2p5("HSMA_LED_G_A[8]"  , hsmc_a_pins[65])
    print_2p5("HSMA_RX_D_P[0]"   , hsmc_a_pins[66])
    print_2p5("HSMA_GPIO[7]"     , hsmc_a_pins[66])
    print_2p5("HSMA_RX_D_P[1]"   , hsmc_a_pins[67])
    print_2p5("HSMA_GPIO[11]"    , hsmc_a_pins[67])
    print_2p5("HSMA_RX_D_P[2]"   , hsmc_a_pins[68])
    print_2p5("HSMA_GPIO[15]"    , hsmc_a_pins[68])
    print_2p5("HSMA_RX_D_P[3]"   , hsmc_a_pins[69])
    print_2p5("HSMA_GPIO[19]"    , hsmc_a_pins[69])
    print_2p5("HSMA_RX_D_P[4]"   , hsmc_a_pins[70])
    print_2p5("HSMA_GPIO[23]"    , hsmc_a_pins[70])
    print_2p5("HSMA_RX_D_P[5]"   , hsmc_a_pins[71])
    print_2p5("HSMA_GPIO[27]"    , hsmc_a_pins[71])
    print_2p5("HSMA_RX_D_P[6]"   , hsmc_a_pins[72])
    print_2p5("HSMA_GPIO[31]"    , hsmc_a_pins[72])
    print_2p5("HSMA_RX_D_P[7]"   , hsmc_a_pins[73])
    print_2p5("HSMA_GPIO[35]"    , hsmc_a_pins[73])
    print_2p5("HSMA_RX_D_P[8]"   , hsmc_a_pins[74])
    print_2p5("HSMA_LED_R_A[0]"  , hsmc_a_pins[74])
    print_2p5("HSMA_RX_D_P[9]"   , hsmc_a_pins[75])
    print_2p5("HSMA_LED_R_A[1]"  , hsmc_a_pins[75])
    print_2p5("HSMA_RX_D_P[10]"  , hsmc_a_pins[76])
    print_2p5("HSMA_LED_R_A[2]"  , hsmc_a_pins[76])
    print_2p5("HSMA_RX_D_P[11]"  , hsmc_a_pins[77])
    print_2p5("HSMA_LED_R_A[3]"  , hsmc_a_pins[77])
    print_2p5("HSMA_RX_D_P[12]"  , hsmc_a_pins[78])
    print_2p5("HSMA_LED_R_A[4]"  , hsmc_a_pins[78])
    print_2p5("HSMA_RX_D_P[13]"  , hsmc_a_pins[79])
    print_2p5("HSMA_LED_R_A[5]"  , hsmc_a_pins[79])
    print_2p5("HSMA_RX_D_P[14]"  , hsmc_a_pins[80])
    print_2p5("HSMA_LED_R_A[6]"  , hsmc_a_pins[80])
    print_2p5("HSMA_RX_D_P[15]"  , hsmc_a_pins[81])
    print_2p5("HSMA_LED_R_A[7]"  , hsmc_a_pins[81])
    print_2p5("HSMA_RX_D_P[16]"  , hsmc_a_pins[82])
    print_2p5("HSMA_LED_R_A[8]"  , hsmc_a_pins[82])
    print_2p5("HSMA_TX_D_N[0]"   , hsmc_a_pins[83])
    print_2p5("HSMA_GPIO[8]"     , hsmc_a_pins[83])
    print_2p5("HSMA_TX_D_N[1]"   , hsmc_a_pins[84])
    print_2p5("HSMA_GPIO[12]"    , hsmc_a_pins[84])
    print_2p5("HSMA_TX_D_N[2]"   , hsmc_a_pins[85])
    print_2p5("HSMA_GPIO[16]"    , hsmc_a_pins[85])
    print_2p5("HSMA_TX_D_N[3]"   , hsmc_a_pins[86])
    print_2p5("HSMA_GPIO[20]"    , hsmc_a_pins[86])
    print_2p5("HSMA_TX_D_N[4]"   , hsmc_a_pins[87])
    print_2p5("HSMA_GPIO[24]"    , hsmc_a_pins[87])
    print_2p5("HSMA_TX_D_N[5]"   , hsmc_a_pins[88])
    print_2p5("HSMA_GPIO[28]"    , hsmc_a_pins[88])
    print_2p5("HSMA_TX_D_N[6]"   , hsmc_a_pins[89])
    print_2p5("HSMA_GPIO[32]"    , hsmc_a_pins[89])
    print_2p5("HSMA_TX_D_N[7]"   , hsmc_a_pins[90])
    print_2p5("HSMA_GPIO[36]"    , hsmc_a_pins[90])
    print_2p5("HSMA_TX_D_N[8]"   , hsmc_a_pins[91])
    print_2p5("HSMA_LED_G_C[0]"  , hsmc_a_pins[91])
    print_2p5("HSMA_TX_D_N[9]"   , hsmc_a_pins[92])
    print_2p5("HSMA_LED_G_C[1]"  , hsmc_a_pins[92])
    print_2p5("HSMA_TX_D_N[10]"  , hsmc_a_pins[93])
    print_2p5("HSMA_LED_G_C[2]"  , hsmc_a_pins[93])
    print_2p5("HSMA_TX_D_N[11]"  , hsmc_a_pins[94])
    print_2p5("HSMA_LED_G_C[3]"  , hsmc_a_pins[94])
    print_2p5("HSMA_TX_D_N[12]"  , hsmc_a_pins[95])
    print_2p5("HSMA_LED_G_C[4]"  , hsmc_a_pins[95])
    print_2p5("HSMA_TX_D_N[13]"  , hsmc_a_pins[96])
    print_2p5("HSMA_LED_G_C[5]"  , hsmc_a_pins[96])
    print_2p5("HSMA_TX_D_N[14]"  , hsmc_a_pins[97])
    print_2p5("HSMA_LED_G_C[6]"  , hsmc_a_pins[97])
    print_2p5("HSMA_TX_D_N[15]"  , hsmc_a_pins[98])
    print_2p5("HSMA_LED_G_C[7]"  , hsmc_a_pins[98])
    print_2p5("HSMA_TX_D_N[16]"  , hsmc_a_pins[99])
    print_2p5("HSMA_LED_G_C[8]"  , hsmc_a_pins[99])
    print_2p5("HSMA_TX_D_P[0]"   , hsmc_a_pins[100])
    print_2p5("HSMA_GPIO[6]"     , hsmc_a_pins[100])
    print_2p5("HSMA_TX_D_P[1]"   , hsmc_a_pins[101])
    print_2p5("HSMA_GPIO[10]"    , hsmc_a_pins[101])
    print_2p5("HSMA_TX_D_P[2]"   , hsmc_a_pins[102])
    print_2p5("HSMA_GPIO[14]"    , hsmc_a_pins[102])
    print_2p5("HSMA_TX_D_P[3]"   , hsmc_a_pins[103])
    print_2p5("HSMA_GPIO[18]"    , hsmc_a_pins[103])
    print_2p5("HSMA_TX_D_P[4]"   , hsmc_a_pins[104])
    print_2p5("HSMA_GPIO[22]"    , hsmc_a_pins[104])
    print_2p5("HSMA_TX_D_P[5]"   , hsmc_a_pins[105])
    print_2p5("HSMA_GPIO[26]"    , hsmc_a_pins[105])
    print_2p5("HSMA_TX_D_P[6]"   , hsmc_a_pins[106])
    print_2p5("HSMA_GPIO[30]"    , hsmc_a_pins[106])
    print_2p5("HSMA_TX_D_P[7]"   , hsmc_a_pins[107])
    print_2p5("HSMA_GPIO[34]"    , hsmc_a_pins[107])
    print_2p5("HSMA_TX_D_P[8]"   , hsmc_a_pins[108])
    print_2p5("HSMA_LED_R_C[0]"  , hsmc_a_pins[108])
    print_2p5("HSMA_TX_D_P[9]"   , hsmc_a_pins[109])
    print_2p5("HSMA_LED_R_C[1]"  , hsmc_a_pins[109])
    print_2p5("HSMA_TX_D_P[10]"  , hsmc_a_pins[110])
    print_2p5("HSMA_LED_R_C[2]"  , hsmc_a_pins[110])
    print_2p5("HSMA_TX_D_P[11]"  , hsmc_a_pins[111])
    print_2p5("HSMA_LED_R_C[3]"  , hsmc_a_pins[111])
    print_2p5("HSMA_TX_D_P[12]"  , hsmc_a_pins[112])
    print_2p5("HSMA_LED_R_C[4]"  , hsmc_a_pins[112])
    print_2p5("HSMA_TX_D_P[13]"  , hsmc_a_pins[113])
    print_2p5("HSMA_LED_R_C[5]"  , hsmc_a_pins[113])
    print_2p5("HSMA_TX_D_P[14]"  , hsmc_a_pins[114])
    print_2p5("HSMA_LED_R_C[6]"  , hsmc_a_pins[114])
    print_2p5("HSMA_TX_D_P[15]"  , hsmc_a_pins[115])
    print_2p5("HSMA_LED_R_C[7]"  , hsmc_a_pins[115])
    print_2p5("HSMA_TX_D_P[16]"  , hsmc_a_pins[116])
    print_2p5("HSMA_LED_R_C[8]"  , hsmc_a_pins[116])
    hsmc_b_pins = ["F2"  , "F1"  , "D2"  , "D1"  , "Y2"  , "Y1"  , "V2"  , "V1"  , "E4"  , "E3"  ,
                   "C4"  , "C3"  , "W4"  , "W3"  , "U4"  , "U3"  , "N16" , "U15" , "P16" , "L16" ,
                   "C16" , "A16" , "D16" , "B16" , "N17" , "P17" , "H13" , "G14" , "L18" , "L19" ,
                   "K19" , "J18" , "A17" , "B17" , "G18" , "C18" , "D18" , "A19" , "B19" , "C19" ,
                   "M18" , "E18" , "D19" , "F18" , "E19" , "M15" , "N15" , "R16" , "G19" , "AF29", 
                   "T16" , "H19" , "U11" , "J13" , "U12" , "H14" , "T12" , "R12" , "N12" , "N13" ,
                   "M12" , "L12" , "K12" , "J12" , "G12" , "G13" , "F12" , "E12" , "D12" , "C12" ,
                   "B13" , "A13" , "U13" , "T13" , "N14" , "M14" , "U14" , "L15" , "J14" , "J15" ,
                   "G15" , "F14" , "F15" , "E14" , "B14" , "A14" , "C14" , "C15" , "K13" , "C13" ,
                   "P14" , "D15" , "L13" , "D13" , "R14" , "E15" , "AA31", "AU7" , "P13" , "AL30", 
                   "AK30", "M17" ]
    print_pcml1p4("HSMB_RX_P[0]"     , hsmc_b_pins[0])
    print_pcml1p4("HSMB_RX_N[0]"     , hsmc_b_pins[1])
    print_pcml1p4("HSMB_RX_P[1]"     , hsmc_b_pins[2])
    print_pcml1p4("HSMB_RX_N[1]"     , hsmc_b_pins[3])
    print_pcml1p4("HSMB_RX_P[2]"     , hsmc_b_pins[4])
    print_pcml1p4("HSMB_RX_N[2]"     , hsmc_b_pins[5])
    print_pcml1p4("HSMB_RX_P[3]"     , hsmc_b_pins[6])
    print_pcml1p4("HSMB_RX_N[3]"     , hsmc_b_pins[7])
    print_pcml1p4("HSMB_TX_P[0]"     , hsmc_b_pins[8])
    print_pcml1p4("HSMB_TX_N[0]"     , hsmc_b_pins[9])
    print_pcml1p4("HSMB_TX_P[1]"     , hsmc_b_pins[10])
    print_pcml1p4("HSMB_TX_N[1]"     , hsmc_b_pins[11])
    print_pcml1p4("HSMB_TX_P[2]"     , hsmc_b_pins[12])
    print_pcml1p4("HSMB_TX_N[2]"     , hsmc_b_pins[13])
    print_pcml1p4("HSMB_TX_P[3]"     , hsmc_b_pins[14])
    print_pcml1p4("HSMB_TX_N[3]"     , hsmc_b_pins[15])
    print_2p5    ("HSMB_CLK_IN_N[2]" , hsmc_b_pins[16])
    print_2p5    ("HSMB_LED_G_A[9]"  , hsmc_b_pins[16])
    print_2p5    ("HSMB_CLK_IN_P[1]" , hsmc_b_pins[17])
    print_2p5    ("HSMB_GPIO[39]"    , hsmc_b_pins[17])
    print_2p5    ("HSMB_CLK_IN_P[2]" , hsmc_b_pins[18])
    print_2p5    ("HSMB_LED_R_A[9]"  , hsmc_b_pins[18])
    print_2p5    ("HSMB_CLK_OUT[0]"  , hsmc_b_pins[19])
    print_2p5    ("HSMB_GPIO[0]"     , hsmc_b_pins[19])
    print_2p5    ("HSMB_CLK_OUT_N[1]", hsmc_b_pins[20])
    print_2p5    ("HSMB_CLK_OUT_N[2]", hsmc_b_pins[21])
    print_2p5    ("HSMB_LED_G_C[9]"  , hsmc_b_pins[21])
    print_2p5    ("HSMB_CLK_OUT_P[1]", hsmc_b_pins[22])
    print_2p5    ("HSMB_GPIO[38]"    , hsmc_b_pins[22])
    print_2p5    ("HSMB_CLK_OUT_P[2]", hsmc_b_pins[23])
    print_2p5    ("HSMB_LED_R_C[9]"  , hsmc_b_pins[23])
    print_cmos2p5("HSMB_A[0]"        , hsmc_b_pins[24])
    print_cmos2p5("HSMB_GPIO[9]"     , hsmc_b_pins[24])
    print_cmos2p5("HSMB_A[1]"        , hsmc_b_pins[25])
    print_cmos2p5("HSMB_GPIO[11]"    , hsmc_b_pins[25])
    print_cmos2p5("HSMB_A[2]"        , hsmc_b_pins[26])
    print_cmos2p5("HSMB_GPIO[13]"    , hsmc_b_pins[26])
    print_cmos2p5("HSMB_A[3]"        , hsmc_b_pins[27])
    print_cmos2p5("HSMB_GPIO[15]"    , hsmc_b_pins[27])
    print_cmos2p5("HSMB_A[4]"        , hsmc_b_pins[28])
    print_cmos2p5("HSMB_GPIO[17]"    , hsmc_b_pins[28])
    print_cmos2p5("HSMB_A[5]"        , hsmc_b_pins[29])
    print_cmos2p5("HSMB_GPIO[25]"    , hsmc_b_pins[29])
    print_cmos2p5("HSMB_A[6]"        , hsmc_b_pins[30])
    print_cmos2p5("HSMB_GPIO[27]"    , hsmc_b_pins[30])
    print_cmos2p5("HSMB_A[7]"        , hsmc_b_pins[31])
    print_cmos2p5("HSMB_GPIO[29]"    , hsmc_b_pins[31])
    print_cmos2p5("HSMB_A[8]"        , hsmc_b_pins[32])
    print_cmos2p5("HSMB_GPIO[31]"    , hsmc_b_pins[32])
    print_cmos2p5("HSMB_A[9]"        , hsmc_b_pins[33])
    print_cmos2p5("HSMB_GPIO[33]"    , hsmc_b_pins[33])
    print_cmos2p5("HSMB_A[10]"       , hsmc_b_pins[34])
    print_cmos2p5("HSMB_LED_G_A[0]"  , hsmc_b_pins[34])
    print_cmos2p5("HSMB_A[11]"       , hsmc_b_pins[35])
    print_cmos2p5("HSMB_LED_R_A[1]"  , hsmc_b_pins[35])
    print_cmos2p5("HSMB_A[12]"       , hsmc_b_pins[36])
    print_cmos2p5("HSMB_LED_G_A[1]"  , hsmc_b_pins[36])
    print_cmos2p5("HSMB_A[13]"       , hsmc_b_pins[37])
    print_cmos2p5("HSMB_LED_R_A[2]"  , hsmc_b_pins[37])
    print_cmos2p5("HSMB_A[14]"       , hsmc_b_pins[38])
    print_cmos2p5("HSMB_LED_G_A[2]"  , hsmc_b_pins[38])
    print_cmos2p5("HSMB_A[15]"       , hsmc_b_pins[39])
    print_cmos2p5("HSMB_LED_G_A[4]"  , hsmc_b_pins[39])
    print_cmos2p5("HSMB_ADDR_CMD[0]" , hsmc_b_pins[40])
    print_cmos2p5("HSMB_GPIO[4]"     , hsmc_b_pins[40])
    print_cmos2p5("HSMB_BA[0]"       , hsmc_b_pins[41])
    print_cmos2p5("HSMB_LED_R_A[5]"  , hsmc_b_pins[41])
    print_cmos2p5("HSMB_BA[1]"       , hsmc_b_pins[42])
    print_cmos2p5("HSMB_LED_G_A[5]"  , hsmc_b_pins[42])
    print_cmos2p5("HSMB_BA[2]"       , hsmc_b_pins[43])
    print_cmos2p5("HSMB_LED_R_A[6]"  , hsmc_b_pins[43])
    print_cmos2p5("HSMB_BA[3]"       , hsmc_b_pins[44])
    print_cmos2p5("HSMB_LED_G_A[6]"  , hsmc_b_pins[44])
    print_cmos2p5("HSMB_C_N"         , hsmc_b_pins[45])
    print_cmos2p5("HSMB_C_P"         , hsmc_b_pins[46])
    print_cmos2p5("HSMB_CASN"        , hsmc_b_pins[47])
    print_cmos2p5("HSMB_GPIO[5]"     , hsmc_b_pins[47])
    print_cmos2p5("HSMB_CKE"         , hsmc_b_pins[48])
    print_cmos2p5("HSMB_LED_R_A[8]"  , hsmc_b_pins[48])
    print_cmos2p5("HSMB_CLK_IN[0]"   , hsmc_b_pins[49])
    print_cmos2p5("HSMB_GPIO[1]"     , hsmc_b_pins[49])
    print_cmos2p5("HSMB_CLK_IN_N[1]" , hsmc_b_pins[50])
    print_cmos2p5("HSMB_CSN"         , hsmc_b_pins[51])
    print_cmos2p5("HSMB_LED_G_A[8]"  , hsmc_b_pins[51])
    print_cmos2p5("HSMB_DM[0]"       , hsmc_b_pins[52])
    print_cmos2p5("HSMB_GPIO[7]"     , hsmc_b_pins[52])
    print_cmos2p5("HSMB_DM[1]"       , hsmc_b_pins[53])
    print_cmos2p5("HSMB_GPIO[23]"    , hsmc_b_pins[53])
    print_cmos2p5("HSMB_DM[2]"       , hsmc_b_pins[54])
    print_cmos2p5("HSMB_LED_R_A[0]"  , hsmc_b_pins[54])
    print_cmos2p5("HSMB_DM[3]"       , hsmc_b_pins[55])
    print_cmos2p5("HSMB_LED_R_A[4]"  , hsmc_b_pins[55])
    print_cmos2p5("HSMB_DQ[0]"       , hsmc_b_pins[56])
    print_cmos2p5("HSMB_GPIO[6]"     , hsmc_b_pins[56])
    print_cmos2p5("HSMB_DQ[1]"       , hsmc_b_pins[57])
    print_cmos2p5("HSMB_GPIO[8]"     , hsmc_b_pins[57])
    print_cmos2p5("HSMB_DQ[2]"       , hsmc_b_pins[58])
    print_cmos2p5("HSMB_GPIO[10]"    , hsmc_b_pins[58])
    print_cmos2p5("HSMB_DQ[3]"       , hsmc_b_pins[59])
    print_cmos2p5("HSMB_GPIO[12]"    , hsmc_b_pins[59])
    print_cmos2p5("HSMB_DQ[4]"       , hsmc_b_pins[60])
    print_cmos2p5("HSMB_GPIO[14]"    , hsmc_b_pins[60])
    print_cmos2p5("HSMB_DQ[5]"       , hsmc_b_pins[61])
    print_cmos2p5("HSMB_GPIO[16]"    , hsmc_b_pins[61])
    print_cmos2p5("HSMB_DQ[6]"       , hsmc_b_pins[62])
    print_cmos2p5("HSMB_GPIO[18]"    , hsmc_b_pins[62])
    print_cmos2p5("HSMB_DQ[7]"       , hsmc_b_pins[63])
    print_cmos2p5("HSMB_GPIO[20]"    , hsmc_b_pins[63])
    print_cmos2p5("HSMB_DQ[8]"       , hsmc_b_pins[64])
    print_cmos2p5("HSMB_GPIO[22]"    , hsmc_b_pins[64])
    print_cmos2p5("HSMB_DQ[9]"       , hsmc_b_pins[65])
    print_cmos2p5("HSMB_GPIO[24]"    , hsmc_b_pins[65])
    print_cmos2p5("HSMB_DQ[10]"      , hsmc_b_pins[66])
    print_cmos2p5("HSMB_GPIO[26]"    , hsmc_b_pins[66])
    print_cmos2p5("HSMB_DQ[11]"      , hsmc_b_pins[67])
    print_cmos2p5("HSMB_GPIO[28]"    , hsmc_b_pins[67])
    print_cmos2p5("HSMB_DQ[12]"      , hsmc_b_pins[68])
    print_cmos2p5("HSMB_GPIO[30]"    , hsmc_b_pins[68])
    print_cmos2p5("HSMB_DQ[13]"      , hsmc_b_pins[69])
    print_cmos2p5("HSMB_GPIO[32]"    , hsmc_b_pins[69])
    print_cmos2p5("HSMB_DQ[14]"      , hsmc_b_pins[70])
    print_cmos2p5("HSMB_GPIO[34]"    , hsmc_b_pins[70])
    print_cmos2p5("HSMB_DQ[15]"      , hsmc_b_pins[71])
    print_cmos2p5("HSMB_GPIO[36]"    , hsmc_b_pins[71])
    print_cmos2p5("HSMB_DQ[16]"      , hsmc_b_pins[72])
    print_cmos2p5("HSMB_LED_R_C[0]"  , hsmc_b_pins[72])
    print_cmos2p5("HSMB_DQ[17]"      , hsmc_b_pins[73])
    print_cmos2p5("HSMB_LED_G_C[0]"  , hsmc_b_pins[73])
    print_cmos2p5("HSMB_DQ[18]"      , hsmc_b_pins[74])
    print_cmos2p5("HSMB_LED_R_C[1]"  , hsmc_b_pins[74])
    print_cmos2p5("HSMB_DQ[19]"      , hsmc_b_pins[75])
    print_cmos2p5("HSMB_LED_G_C[1]"  , hsmc_b_pins[75])
    print_cmos2p5("HSMB_DQ[20]"      , hsmc_b_pins[76])
    print_cmos2p5("HSMB_LED_R_C[2]"  , hsmc_b_pins[76])
    print_cmos2p5("HSMB_DQ[21]"      , hsmc_b_pins[77])
    print_cmos2p5("HSMB_LED_G_C[2]"  , hsmc_b_pins[77])
    print_cmos2p5("HSMB_DQ[22]"      , hsmc_b_pins[78])
    print_cmos2p5("HSMB_LED_R_C[3]"  , hsmc_b_pins[78])
    print_cmos2p5("HSMB_DQ[23]"      , hsmc_b_pins[79])
    print_cmos2p5("HSMB_LED_G_C[3]"  , hsmc_b_pins[79])
    print_cmos2p5("HSMB_DQ[24]"      , hsmc_b_pins[80])
    print_cmos2p5("HSMB_LED_R_C[4]"  , hsmc_b_pins[80])
    print_cmos2p5("HSMB_DQ[25]"      , hsmc_b_pins[81])
    print_cmos2p5("HSMB_LED_G_C[4]"  , hsmc_b_pins[81])
    print_cmos2p5("HSMB_DQ[26]"      , hsmc_b_pins[82])
    print_cmos2p5("HSMB_LED_R_C[5]"  , hsmc_b_pins[82])
    print_cmos2p5("HSMB_DQ[27]"      , hsmc_b_pins[83])
    print_cmos2p5("HSMB_LED_G_C[5]"  , hsmc_b_pins[83])
    print_cmos2p5("HSMB_DQ[28]"      , hsmc_b_pins[84])
    print_cmos2p5("HSMB_LED_R_C[6]"  , hsmc_b_pins[84])
    print_cmos2p5("HSMB_DQ[29]"      , hsmc_b_pins[85])
    print_cmos2p5("HSMB_LED_G_C[6]"  , hsmc_b_pins[85])
    print_cmos2p5("HSMB_DQ[30]"      , hsmc_b_pins[86])
    print_cmos2p5("HSMB_LED_R_C[7]"  , hsmc_b_pins[86])
    print_cmos2p5("HSMB_DQ[31]"      , hsmc_b_pins[87])
    print_cmos2p5("HSMB_LED_G_C[7]"  , hsmc_b_pins[87])
    print_cmos2p5("HSMB_DQS_N[0]"    , hsmc_b_pins[88])
    print_cmos2p5("HSMB_GPIO[21]"    , hsmc_b_pins[88])
    print_cmos2p5("HSMB_DQS_N[1]"    , hsmc_b_pins[89])
    print_cmos2p5("HSMB_GPIO[37]"    , hsmc_b_pins[89])
    print_cmos2p5("HSMB_DQS_N[2]"    , hsmc_b_pins[90])
    print_cmos2p5("HSMB_LED_G_A[3]"  , hsmc_b_pins[90])
    print_cmos2p5("HSMB_DQS_N[3]"    , hsmc_b_pins[91])
    print_cmos2p5("HSMB_LED_G_A[7]"  , hsmc_b_pins[91])
    print_cmos2p5("HSMB_DQS_P[0]"    , hsmc_b_pins[92])
    print_cmos2p5("HSMB_GPIO[19]"    , hsmc_b_pins[92])
    print_cmos2p5("HSMB_DQS_P[1]"    , hsmc_b_pins[93])
    print_cmos2p5("HSMB_GPIO[35]"    , hsmc_b_pins[93])
    print_cmos2p5("HSMB_DQS_P[2]"    , hsmc_b_pins[94])
    print_cmos2p5("HSMB_LED_R_A[3]"  , hsmc_b_pins[94])
    print_cmos2p5("HSMB_DQS_P[3]"    , hsmc_b_pins[95])
    print_cmos2p5("HSMB_LED_R_A[7]"  , hsmc_b_pins[95])
    print_2p5    ("JTAG_TCK"         , hsmc_b_pins[96])
    print_2p5    ("HSMB_PRSNTN"      , hsmc_b_pins[97])
    print_cmos2p5("HSMB_RASN"        , hsmc_b_pins[98])
    print_cmos2p5("HSMB_GPIO[3]"     , hsmc_b_pins[98])
    print_cmos2p5("HSMB_SCL"         , hsmc_b_pins[99])
    print_cmos2p5("HSMB_SDA"         , hsmc_b_pins[100])
    print_pcml1p4("HSMB_WEN"         , hsmc_b_pins[101])
    print_pcml1p4("HSMB_GPIO[2]"     , hsmc_b_pins[101])
print_hsmc()

def print_config():
  print(f"#============================================================")
  print(f"# CONFIGURE")
  print(f"#============================================================")
  print(f"set_global_assignment -name MIN_CORE_JUNCTION_TEMP 0")
  print(f"set_global_assignment -name MAX_CORE_JUNCTION_TEMP 85")
print_config()
